apiVersion: apps/v1
kind: Deployment
metadata:
  name: uber-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uber
  template:
    metadata:
      labels:
        app: uber
    spec:
      containers:
      - name: uber
        image: "865893227318.dkr.ecr.us-east-1.amazonaws.com/uberapp"
        ports:
        - containerPort: 3000
